name: Website Monitor

on:
  schedule:
    # Runs the job every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger of the workflow
  
jobs:
  check_websites:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository to the runner
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies from requirements.txt if present
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run the Python script
      - name: Run Website Monitor Script
        run: |
          python scripts/check_status.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
